{"name": "test_login_failed[case0]", "status": "passed", "attachments": [{"name": "stderr", "source": "4e88fc96-fb8c-457c-bd8a-d9d3cb9ebcd9-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'title': '用户名错误', 'user': 'helloworl', 'passwd': 'rabbit123', 'check': '账号或密码不正确'}"}], "start": 1674741103325, "stop": 1674741104171, "uuid": "cd569181-ed08-4b2e-b948-74084f3bc817", "historyId": "d6d29b3277811a2e7673b1dd04231293", "testCaseId": "a30a453503605050407c31ba0e444078", "fullName": "testcase.test_user_login.TestLogin#test_login_failed", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('user_refresh_page')"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "linjie"}, {"name": "thread", "value": "6844-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_user_login"}]}